// generated by scripts/build.mjs from src/ — do not edit this file directly.

// enterprise-compliance — Host 端可安装插件
// 企业级一体化合规：SOC2/GDPR 合规自检、敏感信息脱敏、操作审计追溯。
// 使用真实 Host API：ctx.tools.register(defineTool(...))、ctx.on(...)、
// ctx.get(...)、ctx.settings.register(...)。纯 JS ESM，无需编译即可加载。
import { defineTool } from "@deepseek-ai/dsh-tools";
import z from "@deepseek-ai/schemastery";
import { RULES, redact, redactDeep } from "./redact.js";

export const name = "enterprise-compliance";

export const inject = ["tools", "settings"];

const AUDIT_CAP = 500;
const STATUS_NS = "enterprise-compliance";

// Host 维护的合规状态命名空间（Client 设置卡片通过 settingsScope 订阅读取）。
const StatusSchema = z.object({
  score: z.number().default(0),
  passed: z.number().default(0),
  total: z.number().default(7),
  auditCount: z.number().default(0),
  items: z.array(z.object({
    id: z.string(),
    status: z.string(),
    control: z.string(),
    detail: z.string(),
  })).default([]),
  recent: z.array(z.object({
    time: z.number(),
    tool: z.string(),
    ok: z.boolean(),
    sessionId: z.string().default(""),
  })).default([]),
});

export function apply(ctx) {
  // ---------------- 操作审计日志（内存环形缓冲） ----------------
  const audit = []

  function pushAudit(entry) {
    audit.push(entry)
    if (audit.length > AUDIT_CAP) audit.splice(0, audit.length - AUDIT_CAP)
  }

  // ---------------- SOC2/GDPR 合规自检 ----------------
  function complianceReport() {
    const sandbox = ctx.get("sandboxPolicy")
    const approval = ctx.get("approval")
    const persistence = ctx.get("sessionPersistence")
    const creds = ctx.get("credentials")
    const telemetry = ctx.get("sessionTelemetry")
    const defaultMode = sandbox ? String(sandbox.defaultMode) : "unknown"
    const sharing = telemetry ? String(telemetry.sharing) : "not-configured"
    const workspaceRoot = sandbox && typeof sandbox.workspaceRoot === "string" ? sandbox.workspaceRoot : null
    const sandboxSafe = defaultMode !== "danger-full-access"
    const items = [
      { id: "sandbox", standard: "SOC2", control: "CC6.1 文件沙箱隔离", status: sandboxSafe ? "pass" : "warn", detail: "默认沙箱模式: " + defaultMode },
      { id: "approval", standard: "SOC2", control: "CC6.2 权限审批", status: approval ? "pass" : "fail", detail: approval ? "审批服务已挂载" : "未检测到审批服务" },
      { id: "audit", standard: "SOC2", control: "CC7.2 操作审计", status: "pass", detail: "审计采集已启用，当前 " + audit.length + " 条" },
      { id: "redaction", standard: "SOC2/GDPR", control: "CC7.3 / Art.25 敏感数据脱敏", status: "pass", detail: "脱敏引擎已启用（" + RULES.length + " 类规则）" },
      { id: "credentials", standard: "SOC2", control: "CC6.6 凭证管理", status: creds ? "pass" : "warn", detail: creds ? "凭证服务已挂载" : "未检测到凭证服务" },
      { id: "persistence", standard: "SOC2", control: "A1.2 持久化日志", status: persistence ? "pass" : "warn", detail: persistence ? "会话持久化已挂载" : "未检测到持久化" },
      { id: "telemetry", standard: "GDPR", control: "Art.5 导出数据最小化", status: "pass", detail: "遥测导出已脱敏，共享策略: " + sharing },
    ]
    const passed = items.filter((i) => i.status === "pass").length
    return {
      score: items.length ? Math.round((passed / items.length) * 100) : 0,
      passed,
      total: items.length,
      items,
      runtime: { sandboxMode: defaultMode, telemetrySharing: sharing, workspaceRoot },
      generatedAt: Date.now(),
    }
  }

  function textReport() {
    const r = complianceReport()
    const lines = r.items.map((i) => "[" + i.status.toUpperCase() + "] " + i.control + " — " + i.detail)
    return "合规评分: " + r.score + "/100 (通过 " + r.passed + "/" + r.total + ")\n" + lines.join("\n") + "\n运行时: 沙箱=" + r.runtime.sandboxMode + ", 遥测共享=" + r.runtime.telemetrySharing
  }

  // ---------------- 合规状态桥（供 Client 卡片读取） ----------------
  const settings = ctx.get("settings")
  let statusScope = undefined
  if (settings !== undefined && typeof settings.register === "function") {
    try {
      statusScope = settings.register(STATUS_NS, StatusSchema, {})
    } catch (e) {
      console.error("[enterprise-compliance] settings.register failed:", e)
      statusScope = undefined
    }
  }

  let lastPublish = 0
  let lastSent = null
  function publishStatus() {
    if (statusScope === undefined) return
    try {
      if (Date.now() - lastPublish < 2000) return
      lastPublish = Date.now()
      const r = complianceReport()
      const patch = {
        score: r.score,
        passed: r.passed,
        total: r.total,
        auditCount: audit.length,
        items: r.items.map((i) => ({ id: i.id, status: i.status, control: i.control, detail: i.detail })),
        recent: audit.slice(-20).reverse().map((e) => ({ time: e.time, tool: e.tool, ok: e.ok, sessionId: e.sessionId || undefined })),
      }
      const key = JSON.stringify(patch)
      if (key === lastSent) return // 无变化则不重复写盘（settings.update 会无条件 persist）
      lastSent = key
      statusScope.update(patch).catch(() => {})
    } catch (e) { /* 状态发布不得影响审计流水线 */ }
  }

  // ---------------- 操作审计采集（工具结果脱敏入账） ----------------
  ctx.on("tools/result", (exec, result) => {
    try {
      const tool = exec && typeof exec.name === "string" ? exec.name : "unknown"
      const args = exec && exec.args !== undefined ? redactDeep(exec.args, 0) : null
      const ok = !!(result && result.ok !== false)
      const error = result && result.error ? String(result.error) : null
      let sessionId = null
      try {
        const agent = exec && exec.agent
        if (agent && agent.session && typeof agent.session.id === "string") sessionId = agent.session.id
      } catch (e) { /* ignore */ }
      pushAudit({ time: Date.now(), tool, ok, error, args, sessionId })
      publishStatus()
    } catch (e) { /* 审计不得打断工具流水线 */ }
  })

  // ---------------- 遥测导出脱敏（GDPR 数据最小化） ----------------
  ctx.on("session-telemetry/record", (record, next) => {
    const base = next()
    try {
      return base && typeof base === "object" ? redactDeep(base, 0) : base
    } catch (e) {
      return base
    }
  })

  // 周期性刷新状态（如遥测共享策略变化），5s 一次，随 Fiber 自动清理。
  const timer = ctx.get("timer")
  if (timer !== undefined && typeof timer.interval === "function") {
    ctx.effect(() => timer.interval(() => publishStatus(), 5000), "enterprise-compliance: status refresh")
  }
  publishStatus()

  // ---------------- 模型可见合规工具 ----------------
  ctx.tools.register(defineTool({
    name: "compliance_report",
    description: "运行企业合规自检（SOC2/GDPR），返回各项检查状态、总体评分与运行时事实。",
    parameters: {},
    output: { schema: { type: "json" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    execute() { return Promise.resolve(textReport()) },
  }))

  ctx.tools.register(defineTool({
    name: "compliance_redact",
    description: "对给定文本做敏感信息脱敏（邮箱、手机号、身份证、银行卡、API Key、JWT、私钥等），返回脱敏结果与命中统计。",
    parameters: { text: { type: "string", required: true, description: "需要脱敏的原始文本" } },
    output: { schema: { type: "json" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    execute(args) {
      const r = redact(String(args && args.text !== undefined ? args.text : ""))
      const summary = r.findings.length ? r.findings.map((f) => f.type + "x" + f.count).join(", ") : "无敏感信息"
      return Promise.resolve("命中: " + summary + "\n\n" + r.text)
    },
  }))

  ctx.tools.register(defineTool({
    name: "compliance_audit",
    description: "查询最近的操作审计日志（工具调用时间、名称、是否成功、脱敏后的参数、会话）。",
    parameters: { limit: { type: "number", description: "返回最近 N 条（默认 20）" } },
    output: { schema: { type: "json" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    execute(args) {
      const limit = Math.min(Math.max(Number(args && args.limit) || 20, 1), 100)
      const rows = audit.slice(-limit).reverse().map((e) => {
        const t = new Date(e.time).toISOString()
        return t + " | " + e.tool + " | " + (e.ok ? "OK" : "FAIL") + (e.error ? " (" + e.error + ")" : "") + (e.sessionId ? " | session=" + e.sessionId : "")
      })
      return Promise.resolve(rows.length ? rows.join("\n") : "（暂无审计记录）")
    },
  }))
}
