// generated by scripts/build.mjs from src/ — do not edit this file directly.

// enterprise-compliance — 敏感信息脱敏引擎（纯函数、零依赖，可独立测试）
// 9 类规则：邮箱、手机号、身份证、银行卡、API Key、JWT、Bearer、私钥、IP。

export const RULES = [
  { id: 'email', label: 'email', re: /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g },
  { id: 'phone', label: 'phone', re: /\b1[3-9]\d{9}\b/g },
  { id: 'idcard', label: 'id-card', re: /\b\d{17}[\dXx]\b/g },
  { id: 'bankcard', label: 'bank-card', re: /\b\d{16,19}\b/g },
  { id: 'apikey', label: 'api-key', re: /\b(?:sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16}|ghp_[A-Za-z0-9]{36,}|xox[bap]-[A-Za-z0-9-]{10,})\b/g },
  { id: 'jwt', label: 'jwt', re: /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g },
  { id: 'bearer', label: 'bearer', re: /\bBearer\s+[A-Za-z0-9._~+/=-]{20,}/gi },
  { id: 'privatekey', label: 'private-key', re: /-----BEGIN [A-Z ]*PRIVATE KEY-----\n[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g },
  { id: 'ip', label: 'ip', re: /\b\d{1,3}(?:\.\d{1,3}){3}\b/g },
]

export function redact(text) {
  if (typeof text !== 'string') return { text: String(text), findings: [] }
  let out = text
  const counts = {}
  for (const rule of RULES) {
    rule.re.lastIndex = 0
    out = out.replace(rule.re, () => {
      counts[rule.id] = (counts[rule.id] || 0) + 1
      return '[' + rule.label + ']'
    })
  }
  const findings = Object.keys(counts).map((id) => ({ type: id, count: counts[id] }))
  return { text: out, findings }
}

export function redactDeep(value, depth) {
  if (depth > 8) return value
  if (typeof value === 'string') return redact(value).text
  if (Array.isArray(value)) return value.map((v) => redactDeep(v, depth + 1))
  if (value && typeof value === 'object') {
    const out = {}
    for (const key of Object.keys(value)) {
      try { out[key] = redactDeep(value[key], depth + 1) } catch (e) { out[key] = value[key] }
    }
    return out
  }
  return value
}
