#!/usr/bin/env node
// 生成提交产物：把 src/ 的纯 JS 复制到 lib/ 与 client/（附带生成头注释）。
// lib/index.js + client/client.js 已提交，因此 git 安装无需 prepare 构建。
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const banner = "// generated by scripts/build.mjs from src/ — do not edit this file directly.\n\n";

const copies = [
  ["src/redact.js", "lib/redact.js"],
  ["src/index.js", "lib/index.js"],
  ["src/client.js", "client/client.js"],
];

for (const [from, to] of copies) {
  const target = join(root, to);
  await mkdir(dirname(target), { recursive: true });
  const source = await readFile(join(root, from), "utf8");
  await writeFile(target, banner + source);
}

console.log("build: lib/index.js, lib/redact.js, client/client.js synced from src/");
